### ISSUE TITLE
something wrong when I run this code

### ISSUE THREAD

**Issue by yanghlll** [arthur-qiu/LongerCrafter#21]
can anyone plz help me how to fix this error?

INFO:root:Loaded ViT-H-14 model config.
Traceback (most recent call last):
  File "/mnt/sda/Video_Generation/FreeNoise/scripts/evaluation/funcs.py", line 239, in load_checkpoint
    print(state_dict['module'].keys())
KeyError: 'module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sda/Video_Generation/FreeNoise/scripts/evaluation/inference.py", line 137, in <module>
    run_inference(args, gpu_num, rank)
  File "/mnt/sda/Video_Generation/FreeNoise/scripts/evaluation/inference.py", line 51, in run_inference
    model = load_model_checkpoint(model, args.ckpt_path)
  File "/mnt/sda/Video_Generation/FreeNoise/scripts/evaluation/funcs.py", line 248, in load_model_checkpoint
    load_checkpoint(model, ckpt, full_strict=False)
  File "/mnt/sda/Video_Generation/FreeNoise/scripts/evaluation/funcs.py", line 246, in load_checkpoint
    model.load_state_dict(state_dict, strict=full_strict)
  File "/home/.conda/envs/freenoise/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
        size mismatch for scale_arr: copying a param with shape torch.Size([1400]) from checkpoint, the shape in current model is torch.Size([1000]).

if any other details are needed I am happy to share.

**Comment by arthur-qiu** [comment]
I think your checkpoint is not aligned with your config file.

**Comment by yanghlll** [comment]
Thank you for your patient response, my problem has been solved.
